services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: pingpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pingpay

networks:
  pingpay:

volumes:
  pgdata:
