server {
    listen 80;

    location /api {
        root /var/www/server/public;
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/server/public/index.php;
        include fastcgi_params;
    }

    location / {
        proxy_pass http://frontend:4321;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}